modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)

issueTrackerURL="https://github.com/thedarkcolour/Future-MC/issues" # Issues page


#displayURL="https://minecraft.curseforge.com/projects/futuremc" #optional

description='''
Future MC. Adds things meant to enhance the vanilla experience.
''' # A description

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.futuremc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"

    side="BOTH"
# Dependency
[[dependencies.futuremc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

# --------------------------------------------------------- #
# --------------------------------------------------------- #
# --------------------------------------------------------- #

[[mods]] #mandatory
displayName="Future MC" # Name of mod
modId="futuremc" # Modid
version="0.0.1" # Version of futuremc
authors="TheDarkColour" # Author
credits="Herobrine knows all." # Credits