modLoader="kotlinforforge"
loaderVersion="[1.3,)"

[[mods]]
modId="futuremc"
version="${file.jarVersion}"
displayName="Future MC"
credits="Herobrine knows all."
authors="TheDarkColour"
description='''
Backports things from future versions.
'''
[[dependencies.futuremc]]
    modId="forge"
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.futuremc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16]"
    ordering="NONE"
    side="BOTH"
